"""Algorithm package for the educational S-AES implementation."""

from .cryptanalysis import (
    DEFAULT_DIFFERENTIAL_PAIRS,
    DEFAULT_KNOWN_PLAINTEXT,
    KEYSPACE_SIZE,
    DifferentialAttackReport,
    DifferentialObservation,
    KnownPair,
    brute_force_keys_from_known_pair,
    collect_differential_observations,
    filter_keys_with_differentials,
    run_differential_attack,
)
from .saes import (
    DecryptionTrace,
    EncryptionTrace,
    decrypt_bits,
    decrypt_block,
    decrypt_block_with_trace,
    encrypt_bits,
    encrypt_block,
    encrypt_block_with_trace,
)
from .xts import (
    BLOCK_SIZE_BITS,
    BLOCK_SIZE_BYTES,
    CTSBlockTrace,
    XEXBlockTrace,
    XTSTrace,
    decrypt_message,
    decrypt_message_bits,
    decrypt_message_with_trace,
    derive_initial_tweak,
    encrypt_message,
    encrypt_message_bits,
    encrypt_message_with_trace,
    multiply_tweak_by_alpha,
)

__all__ = [
    "BLOCK_SIZE_BITS",
    "BLOCK_SIZE_BYTES",
    "CTSBlockTrace",
    "DEFAULT_DIFFERENTIAL_PAIRS",
    "DEFAULT_KNOWN_PLAINTEXT",
    "DecryptionTrace",
    "DifferentialAttackReport",
    "DifferentialObservation",
    "EncryptionTrace",
    "KEYSPACE_SIZE",
    "KnownPair",
    "XEXBlockTrace",
    "XTSTrace",
    "brute_force_keys_from_known_pair",
    "collect_differential_observations",
    "decrypt_bits",
    "decrypt_block",
    "decrypt_block_with_trace",
    "decrypt_message",
    "decrypt_message_bits",
    "decrypt_message_with_trace",
    "derive_initial_tweak",
    "encrypt_bits",
    "encrypt_block",
    "encrypt_block_with_trace",
    "encrypt_message",
    "encrypt_message_bits",
    "encrypt_message_with_trace",
    "filter_keys_with_differentials",
    "multiply_tweak_by_alpha",
    "run_differential_attack",
]
